[book]
authors = ['thinkgo']
language = 'en'
multilingual = false
src = 'src'
title = 'Rust For Rustaceans 阅读和翻译'
[output.html]
mathjax-support = true
git-repository-url = 'https://github.com/thinkgos/Rust-For-Rustaceans'

[output.html.playground]
editable = true
line-numbers = true

[output.html.fold]
enable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[rust]
edition = '2021'